import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import TrackingProvider from "./Context/TrackingContext";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TrackingProvider>
        <body className={inter.className}>{children}</body>
      </TrackingProvider>
    </html>
  );
}
